### ISSUE TITLE
how to use zora with Deno?

### ISSUE THREAD

**Issue by andreswebs** [lorenzofox3/zora#77] opened 2020-12-12 23:55 UTC
Doing an

```javascript
import { test } from "https://raw.githubusercontent.com/lorenzofox3/zora/master/src/index.ts"
```

gives this error:

```txt
Download https://raw.githubusercontent.com/lorenzofox3/zora/master/src/reporter
Download https://raw.githubusercontent.com/lorenzofox3/zora/master/src/interfaces
Download https://raw.githubusercontent.com/lorenzofox3/zora/master/src/harness
Download https://raw.githubusercontent.com/lorenzofox3/zora/master/src/assertion
error: Import 'https://raw.githubusercontent.com/lorenzofox3/zora/master/src/reporter' failed: 404 Not Found
    at https://raw.githubusercontent.com/lorenzofox3/zora/master/src/index.ts:2:0
```

**Comment by lorenzofox3** [comment] 2020-12-14 09:44
Hello. 

To be honest I don't know: [https://raw.githubusercontent.com/lorenzofox3/zora/master/src/reporter.ts](https://raw.githubusercontent.com/lorenzofox3/zora/master/src/reporter.ts) exists, so it might be a bug in Deno's loader. 

Maybe you can try by using [this bundle file URL](https://unpkg.com/zora@4.0.0/dist/bundle/module.js).

Perhaps @bdchauvette can help you. He is the only Deno's user I am aware of

**Comment by bdchauvette** [comment] 2020-12-14 16:10
You have to use the bundle URL and you won't be able to use any TS interfaces because the declarations use node-style path imports. [Here's a minimal example.](https://repl.it/@bdchauvette/zora-deno-example#index.ts)

The reason you have to use the bundle is that it's pretty much impossible to write TS sources that are compatible with both Deno and `tsc`. The issue is that Deno requires you to include `.ts` in the import path but the `tsc` itself does not allow you to import files ending with `.ts` (see e.g. https://github.com/microsoft/TypeScript/issues/37582). As a result, you can either write TS sources that work with Deno or TS sources that work with `tsc`, but not both.

The reason the declarations don't work is again related to Deno's requirement that imports need to match the exact file name. The Zora typings are not bundled and they use Node-style extensionless paths. So even if you add a `// @deno-types` annotation (see below), it will fail when trying to import the other type files:

```ts
// @deno-types="https://unpkg.com/zora@4.0.1/dist/declarations/index.d.ts"
import { test } from 'https://unpkg.com/zora@4.0.1/dist/bundle/module.js';
```

In my case, I'm writing a cross-platform lib, so I'm writing the tests with Node-style imports, then bundling everything together (with some changes based on target runtime) into tmp files, then running Node, Deno, QuickJS, etc. against the temp files. The only runtime support that I was missing from Zora was the ability to read env vars from the `Deno` object like it does with `process` in Node (#73).

If you're _only_ supporting Deno, you should probably use Deno's builtin test framework or something like [Rhum](https://drash.land/rhum/v1.x/#/) that targets Deno exclusively.

---

@lorenzofox3 -- Sorry for adding some maintenance overhead here :sweat:

I'm actually probably going to end up writing my own testing framework (no issue with Zora, I just prefer Mocha/Jest bdd-style structure for tests), so it might be simpler to revert #73 to avoid any confusion about Deno support :grimacing:

**Comment by lorenzofox3** [comment] 2020-12-15 10:38
Thanks for thorough your feedback @bdchauvette 👍  I'll close this one for now

**Closed by lorenzofox3** 2020-12-15 10:38 UTC
Labels: question
